### ISSUE TITLE
webpack can pack?

### ISSUE THREAD

**Issue by sujiewen** [lceric/vite-vue2-demo#4]
TypeError: Cannot read property 'get' of undefined
    at /Users/lc/Downloads/vite-vue2-demo-master/node_modules/webpack/lib/DefinePlugin.js:292:38
    at SyncHook.eval [as call] (eval at create (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:21:1)
    at SyncHook.lazyCompileHook (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/lc/Downloads/vite-vue2-demo-master/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/lc/Downloads/vite-vue2-demo-master/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/lc/Downloads/vite-vue2-demo-master/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/lc/Downloads/vite-vue2-demo-master/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lc/Downloads/vite-vue2-demo-master/node_modules/tapable/lib/Hook.js:154:20)

**Comment by lceric** [comment]
have a try.
```bash

git pull

rm -rf node_modules

npm i
```
